//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBB.Wsdl.HatDurak
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IBB.Wsdl.HatDurak.WebService1Soap")]
    internal interface IHatDurakSoapClient
    {
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDurak_XML", ReplyAction="*")]
        System.Threading.Tasks.Task<IBB.Wsdl.HatDurak.GetDurak_XMLResponse> GetDurak_XMLAsync(IBB.Wsdl.HatDurak.GetDurak_XMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDurak_json", ReplyAction="*")]
        System.Threading.Tasks.Task<IBB.Wsdl.HatDurak.GetDurak_jsonResponse> GetDurak_jsonAsync(IBB.Wsdl.HatDurak.GetDurak_jsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGaraj_XML", ReplyAction="*")]
        System.Threading.Tasks.Task<IBB.Wsdl.HatDurak.GetGaraj_XMLResponse> GetGaraj_XMLAsync(IBB.Wsdl.HatDurak.GetGaraj_XMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGaraj_json", ReplyAction="*")]
        System.Threading.Tasks.Task<IBB.Wsdl.HatDurak.GetGaraj_jsonResponse> GetGaraj_jsonAsync(IBB.Wsdl.HatDurak.GetGaraj_jsonRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetDurak_XMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDurak_XML", Namespace="http://tempuri.org/", Order=0)]
        public IBB.Wsdl.HatDurak.GetDurak_XMLRequestBody Body;
        
        public GetDurak_XMLRequest()
        {
        }
        
        public GetDurak_XMLRequest(IBB.Wsdl.HatDurak.GetDurak_XMLRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class GetDurak_XMLRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DurakKodu;
        
        public GetDurak_XMLRequestBody()
        {
        }
        
        public GetDurak_XMLRequestBody(string DurakKodu)
        {
            this.DurakKodu = DurakKodu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetDurak_XMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDurak_XMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public IBB.Wsdl.HatDurak.GetDurak_XMLResponseBody Body;
        
        public GetDurak_XMLResponse()
        {
        }
        
        public GetDurak_XMLResponse(IBB.Wsdl.HatDurak.GetDurak_XMLResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class GetDurak_XMLResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetDurak_XMLResult;
        
        public GetDurak_XMLResponseBody()
        {
        }
        
        public GetDurak_XMLResponseBody(System.Xml.Linq.XElement GetDurak_XMLResult)
        {
            this.GetDurak_XMLResult = GetDurak_XMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetDurak_jsonRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDurak_json", Namespace="http://tempuri.org/", Order=0)]
        public IBB.Wsdl.HatDurak.GetDurak_jsonRequestBody Body;
        
        public GetDurak_jsonRequest()
        {
        }
        
        public GetDurak_jsonRequest(IBB.Wsdl.HatDurak.GetDurak_jsonRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class GetDurak_jsonRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DurakKodu;
        
        public GetDurak_jsonRequestBody()
        {
        }
        
        public GetDurak_jsonRequestBody(string DurakKodu)
        {
            this.DurakKodu = DurakKodu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetDurak_jsonResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDurak_jsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public IBB.Wsdl.HatDurak.GetDurak_jsonResponseBody Body;
        
        public GetDurak_jsonResponse()
        {
        }
        
        public GetDurak_jsonResponse(IBB.Wsdl.HatDurak.GetDurak_jsonResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class GetDurak_jsonResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDurak_jsonResult;
        
        public GetDurak_jsonResponseBody()
        {
        }
        
        public GetDurak_jsonResponseBody(string GetDurak_jsonResult)
        {
            this.GetDurak_jsonResult = GetDurak_jsonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetGaraj_XMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGaraj_XML", Namespace="http://tempuri.org/", Order=0)]
        public IBB.Wsdl.HatDurak.GetGaraj_XMLRequestBody Body;
        
        public GetGaraj_XMLRequest()
        {
        }
        
        public GetGaraj_XMLRequest(IBB.Wsdl.HatDurak.GetGaraj_XMLRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class GetGaraj_XMLRequestBody
    {
        
        public GetGaraj_XMLRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetGaraj_XMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGaraj_XMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public IBB.Wsdl.HatDurak.GetGaraj_XMLResponseBody Body;
        
        public GetGaraj_XMLResponse()
        {
        }
        
        public GetGaraj_XMLResponse(IBB.Wsdl.HatDurak.GetGaraj_XMLResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class GetGaraj_XMLResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetGaraj_XMLResult;
        
        public GetGaraj_XMLResponseBody()
        {
        }
        
        public GetGaraj_XMLResponseBody(System.Xml.Linq.XElement GetGaraj_XMLResult)
        {
            this.GetGaraj_XMLResult = GetGaraj_XMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetGaraj_jsonRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGaraj_json", Namespace="http://tempuri.org/", Order=0)]
        public IBB.Wsdl.HatDurak.GetGaraj_jsonRequestBody Body;
        
        public GetGaraj_jsonRequest()
        {
        }
        
        public GetGaraj_jsonRequest(IBB.Wsdl.HatDurak.GetGaraj_jsonRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class GetGaraj_jsonRequestBody
    {
        
        public GetGaraj_jsonRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetGaraj_jsonResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGaraj_jsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public IBB.Wsdl.HatDurak.GetGaraj_jsonResponseBody Body;
        
        public GetGaraj_jsonResponse()
        {
        }
        
        public GetGaraj_jsonResponse(IBB.Wsdl.HatDurak.GetGaraj_jsonResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class GetGaraj_jsonResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetGaraj_jsonResult;
        
        public GetGaraj_jsonResponseBody()
        {
        }
        
        public GetGaraj_jsonResponseBody(string GetGaraj_jsonResult)
        {
            this.GetGaraj_jsonResult = GetGaraj_jsonResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    internal interface IHatDurakSoapClientChannel : IBB.Wsdl.HatDurak.IHatDurakSoapClient, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    internal partial class HatDurakSoapClient : System.ServiceModel.ClientBase<IBB.Wsdl.HatDurak.IHatDurakSoapClient>, IBB.Wsdl.HatDurak.IHatDurakSoapClient
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HatDurakSoapClient() : 
                base(HatDurakSoapClient.GetDefaultBinding(), HatDurakSoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WebService1Soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HatDurakSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(HatDurakSoapClient.GetBindingForEndpoint(endpointConfiguration), HatDurakSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HatDurakSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HatDurakSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HatDurakSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HatDurakSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HatDurakSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IBB.Wsdl.HatDurak.GetDurak_XMLResponse> IBB.Wsdl.HatDurak.IHatDurakSoapClient.GetDurak_XMLAsync(IBB.Wsdl.HatDurak.GetDurak_XMLRequest request)
        {
            return base.Channel.GetDurak_XMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<IBB.Wsdl.HatDurak.GetDurak_XMLResponse> GetDurak_XMLAsync(string DurakKodu)
        {
            IBB.Wsdl.HatDurak.GetDurak_XMLRequest inValue = new IBB.Wsdl.HatDurak.GetDurak_XMLRequest();
            inValue.Body = new IBB.Wsdl.HatDurak.GetDurak_XMLRequestBody();
            inValue.Body.DurakKodu = DurakKodu;
            return ((IBB.Wsdl.HatDurak.IHatDurakSoapClient)(this)).GetDurak_XMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IBB.Wsdl.HatDurak.GetDurak_jsonResponse> IBB.Wsdl.HatDurak.IHatDurakSoapClient.GetDurak_jsonAsync(IBB.Wsdl.HatDurak.GetDurak_jsonRequest request)
        {
            return base.Channel.GetDurak_jsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<IBB.Wsdl.HatDurak.GetDurak_jsonResponse> GetDurak_jsonAsync(string DurakKodu)
        {
            IBB.Wsdl.HatDurak.GetDurak_jsonRequest inValue = new IBB.Wsdl.HatDurak.GetDurak_jsonRequest();
            inValue.Body = new IBB.Wsdl.HatDurak.GetDurak_jsonRequestBody();
            inValue.Body.DurakKodu = DurakKodu;
            return ((IBB.Wsdl.HatDurak.IHatDurakSoapClient)(this)).GetDurak_jsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IBB.Wsdl.HatDurak.GetGaraj_XMLResponse> IBB.Wsdl.HatDurak.IHatDurakSoapClient.GetGaraj_XMLAsync(IBB.Wsdl.HatDurak.GetGaraj_XMLRequest request)
        {
            return base.Channel.GetGaraj_XMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<IBB.Wsdl.HatDurak.GetGaraj_XMLResponse> GetGaraj_XMLAsync()
        {
            IBB.Wsdl.HatDurak.GetGaraj_XMLRequest inValue = new IBB.Wsdl.HatDurak.GetGaraj_XMLRequest();
            inValue.Body = new IBB.Wsdl.HatDurak.GetGaraj_XMLRequestBody();
            return ((IBB.Wsdl.HatDurak.IHatDurakSoapClient)(this)).GetGaraj_XMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IBB.Wsdl.HatDurak.GetGaraj_jsonResponse> IBB.Wsdl.HatDurak.IHatDurakSoapClient.GetGaraj_jsonAsync(IBB.Wsdl.HatDurak.GetGaraj_jsonRequest request)
        {
            return base.Channel.GetGaraj_jsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<IBB.Wsdl.HatDurak.GetGaraj_jsonResponse> GetGaraj_jsonAsync()
        {
            IBB.Wsdl.HatDurak.GetGaraj_jsonRequest inValue = new IBB.Wsdl.HatDurak.GetGaraj_jsonRequest();
            inValue.Body = new IBB.Wsdl.HatDurak.GetGaraj_jsonRequestBody();
            return ((IBB.Wsdl.HatDurak.IHatDurakSoapClient)(this)).GetGaraj_jsonAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap))
            {
                return new System.ServiceModel.EndpointAddress("https://api.ibb.gov.tr/iett/UlasimAnaVeri/HatDurakGuzergah.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return HatDurakSoapClient.GetBindingForEndpoint(EndpointConfiguration.WebService1Soap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return HatDurakSoapClient.GetEndpointAddress(EndpointConfiguration.WebService1Soap);
        }
        
        public enum EndpointConfiguration
        {
            
            WebService1Soap,
        }
    }
}
